### ISSUE TITLE
am-image 怎么得到image的ref ？

### ISSUE THREAD

**Issue by kang558** [hminghe/weex-amui#14]
父组件中使用，报错
this.$refs['image'].save((result) => {
                if (result.success) {
                    this.$notice.toast({ message: '已保存至本地' })
                } else {
                    this.$notice.toast({ message: '保存失败！请稍后再试试~' })
                }
});

**Comment by hminghe** [comment]
暂时可以使用 
`this.$refs.image.image.save`
使用，迟点我把image组件的方法加一下。

**Comment by kang558** [comment]
ok
