### ISSUE TITLE
am-picker

### ISSUE THREAD

**Issue by ecdiy** [hminghe/weex-amui#15]
没有change事件，am-picker-view不是想要的效果，能给picker加个事件吗？

**Comment by bochen111** [comment]
AmPicker 点击确认选择的时候，要点击两次 才能关闭弹窗，而点击关闭则是点击一次就行

**Comment by hminghe** [comment]
> AmPicker 点击确认选择的时候，要点击两次 才能关闭弹窗，而点击关闭则是点击一次就行

我测试没有这个问题。 方便的话提供一下系统，和系统版本。

**Comment by hminghe** [comment]
> 没有change事件，am-picker-view不是想要的效果，能给picker加个事件吗？

可以加一个。

**Comment by bochen111** [comment]
> > AmPicker 点击确认选择的时候，要点击两次 才能关闭弹窗，而点击关闭则是点击一次就行
> 
> 我测试没有这个问题。 方便的话提供一下系统，和系统版本。

安卓系统，安卓4.4.2  机器华为荣耀3c,昨天确定按钮方法里面加了一个 延迟2毫秒关闭 可以暂时解决
