### ISSUE TITLE
@load.native="handleLoad" 调用image的方法无任何作用

### ISSUE THREAD

**Issue by kang558** [hminghe/weex-amui#17]
AmImage 组件 @load.native="handleLoad" 调用image的方法无任何作用

我改了组件像这样，使用和原来的image标签一样，就可以用了
![image](https://user-images.githubusercontent.com/22288837/48177457-9bc37680-e34f-11e8-8b3a-d439b937a7ce.png)

**Comment by hminghe** [comment]
欢迎提 pull request

**Comment by kang558** [comment]
> 欢迎提 pull request
就一行代码，你加上去就行啦  :joy:
this.$emit('load', $event)

**Comment by uncleLian** [comment]
还没修复吗。。。

**Comment by hminghe** [comment]
可以了。
