### ISSUE TITLE
am-picker地址选择器，地区名字过长导致地址换行

### ISSUE THREAD

**Issue by LingCn** [hminghe/weex-amui#18]
#出现如下问题
1、比如新疆维吾尔自治区的地区选择无法滚动最底部 
![image](https://user-images.githubusercontent.com/22288787/49428821-fd0d2700-f7e1-11e8-9dd8-f56e38a9fbd9.png)

2、吉林省地区部分不能对应
![image](https://user-images.githubusercontent.com/22288787/49428837-08605280-f7e2-11e8-84c3-7db880678980.png)

**Comment by NBAUser** [comment]
![image](https://user-images.githubusercontent.com/22288787/49428755-d818b400-f7e1-11e8-9457-c62b298a693b.png)

**Comment by hminghe** [comment]
收到，大概知道什么问题了， 暂时想不到怎么样解决， 建议先控制每个项的字数，不要让他换行。有空我再想办法处理了这问题。

**Comment by NBAUser** [comment]
不能通过css的属性控制自动换成省略号嘛？
