### ISSUE TITLE
0.1.2、0.1.3版本am-date-picker，在iphone下，显示不全，年份无法看到。

### ISSUE THREAD

**Issue by gergulo** [hminghe/weex-amui#24]
![qq 20190304120604](https://user-images.githubusercontent.com/10461140/53710030-36534280-3e76-11e9-86cd-8043a2109b44.png)

**Comment by Mrrrc** [comment]
我也有这个问题，不知道怎么解决。
还有如果在XR上打开的话，picker view的高度也有问题，已经提了PR了。

**Comment by hminghe** [comment]
奇怪的是我的不IPHONE6 不会。  你用的weex是什么版本的？  是直接扫文档的例子就会这样吗？@gergulo

**Comment by Mrrrc** [comment]
扫文档的例子没问题，web 也没问题。但是 iOS 本地不行，iPhone 6 和 XR 都是了，问题好像出在这里：[#18](https://github.com/hminghe/weex-amui/commit/10a5adf35e480cf302c7050b5452ce2ed4683a15)

但我实在不知道该如何解决
