### ISSUE TITLE
ios 9.2 中am-date-picker报错, ios 11.4中正常

### ISSUE THREAD

**Issue by wtowto7207** [hminghe/weex-amui#3]
![Alt text](https://ws1.sinaimg.cn/mw690/9290cd97gy1fsoeonyy0nj20ku1120tt.jpg)
![Alt text](https://ws1.sinaimg.cn/mw690/9290cd97gy1fsoeoo3znyj20ku1120xg.jpg)

**Comment by hminghe** [comment]
晚点修复
