### ISSUE TITLE
主题里的品牌色有没有非入侵式的修改方式

### ISSUE THREAD

**Issue by phoenixsky** [hminghe/weex-amui#5]
通过Eros引入的amui,本身有自己的主题色彩.现在想修改控件的颜色,除了在`node_modules`目录中,将`variable.less`中的值修改,有没有别的更好的方式

**Comment by hminghe** [comment]
下个版本整理 variable.less 文件， 和出教程。
如果着急可以参考 `https://github.com/hminghe/weex-amui-template/blob/master/template/configs/utils.js` 这个文件的第8行和第50行。
主要是给less传`modifyVars`参数

**Comment by hminghe** [comment]
自定义主题已上线。 请查看文档 https://hminghe.github.io/weex-amui/#/docs/theme
