### ISSUE TITLE
am-picker 组件滚动选择时，内容不在选择框中间。

### ISSUE THREAD

**Issue by zhangning12328** [hminghe/weex-amui#7]
给am-picker传入列表时，在滚动时，会出现选择项偏出选择框的情况。而且在点选后，选中的内容与显示的内容不一致。如列表项1-9，显示当前选中的是5，但实际选中的2。
<img width="339" alt="image" src="https://user-images.githubusercontent.com/38879507/42455359-9f29d232-83c4-11e8-81cc-8daaa383cece.png">

**Comment by zhangning12328** [comment]
ios 10.3

**Comment by hminghe** [comment]
你的weex-amui是什么版本？

**Comment by hminghe** [comment]
更新到最新版本应该是没有问题的.ios久的版本是有问题的

**Comment by zhangning12328** [comment]
import { AmPicker } from 'weex-amui'
编译后用weexPlayground打开.weex页面，报错:SyntaxError: Unexpected keyword 'export'
之前在eros项目里，也是这样引用的，当时是可以的。
已经安装了 babel-preset-stage-0 babel-plugin-component ，也按照文档配置了。

请问会是什么原因？

**Comment by hminghe** [comment]
贴你的配置上来看看
